[package]
name = "tenk"
version = "0.1.0"
authors = ["Willem Wyndham <willem@near.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { git = "https://github.com/willemneal/near-sdk-rs", branch = "release"}
near-contract-standards = { git = "https://github.com/willemneal/near-sdk-rs", branch = "release" }
serde = "1.0.0"
near-units = "0.2.0"
serde_with = "1.0.0"

[dev-dependencies]
rand = "0.7.2"
rand_xorshift = "0.2.0"

[features]
default = []
mainnet = []
on_sale = []
airdrop = []
